import type { Metadata } from "next";
import "../public/fonts/style.css";
import "../styles/sass/main.scss";
import "./globals.css";

import NavBar from "@/components/NavBar/page";
import toast, { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "درمانگاه فرهنگیان  نیشابور",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className="light">
      <body className="w-full bg-gray-50 text-gray-900 min-h-screen">
        <Toaster position="top-center" />

        {/* ناوبری عمومی */}

        {/* محتوای اصلی */}
        <main className="flex flex-col px-4 sm:px-6 md:px-12 lg:px-20 py-6 gap-12">
          {children}
        </main>
      </body>
    </html>
  );
}
