import type { Metadata } from "next";
import '../public/fonts/style.css';
import '../styles/sass/main.scss';
import "./globals.css";
import NavBar from "@/components/NavBar/page";
import toast, { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className="light">
      <body className=" w-full bg-gray-50 text-gray-900">
        <Toaster />
        <div className="flex flex-row min-h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
